### ISSUE TITLE
Occured Crash with Liteloader 2.1.0

### ISSUE THREAD

**Issue by VoryWork** [HuoHuas001/HeadShow#1]
[Crashed!]
-- Unhandled Exception in -> VCRUNTIME140.dll
-- Exception Code: 0xC0000005
-- C++ STL Exception detected!

[TrackBack] Function memcpy at 0x7FFAE6CF12F0  [VCRUNTIME140.dll]
-- At File [TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,std::allocator<char> > at 0x7FFAD3CB6040  [HeadShow.dll]
-- At File C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\include\xstring : Line 2467 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function updateHead at 0x7FFAD3C90430  [HeadShow.dll]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 255 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function THookTemplate<-2025466159863359608,-2025466159863359608>::_hook at 0x7FFAD3C91C30  [HeadShow.dll]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerLevel::tick at 0x7FF64944B3C0  [bedrock_server_mod.exe]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Schedule::nextTick at 0x7FFACDB56A10  [LiteLoader.dll]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF6499502D0  [bedrock_server_mod.exe]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function ServerInstance::_update at 0x7FF649425610  [bedrock_server_mod.exe]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function <lambda_5d63f534eeadf9e385a3ddce5663beb8>::operator() at 0x7FF64941D5F0  [bedrock_server_mod.exe]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_5d63f534eeadf9e385a3ddce5663beb8> >,0> at 0x7FF649402240  [bedrock_server_mod.exe]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function configthreadlocale at 0x7FFAEC5B1B20  [ucrtbase.dll]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function BaseThreadInitThunk at 0x7FFAEDC27020  [KERNEL32.DLL]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function RtlUserThreadStart at 0x7FFAEEE02630  [ntdll.dll]
-- At File D:\a\HeadShow\HeadShow\Template\Plugin.cpp : Line 274 
[TrackBack] Function ???????? at 0x????????

**Comment by HuoHuas001** [comment]
How is it caused? Can you give me the method of reproduction
